# -*- coding: utf-8 -*-
"""brazilian_feelings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AE1NN509rye5wyhBQ6VNbDXs3liqgpbK

# Análise de sentimentos por região

Uma das áreas de ciência de dados que tem apresentado grande crescimento é a análise de sentimentos.

Nesse notebook vamos ver uma forma de analisar como está o sentimento dos usuários do twitter sobre ~~politica~~ um determinado assunto. Além disso essa análise poderá ser feitas sobre as regiões, visto que um mesmo assunto pode causar diferentes reações em locais variados.

## Pré-requisitos

- Python3
- TextBlob
- TweePy
- Numpy
- Conta no twitter
"""

!pip install tweepy textblob numpy
!python -m textblob.download_corpora

"""## Perfil de desenvolvedor

Após instalar as bibliotecas será necessário (se você não possuir ainda) criar uma conta de desenvolvedor no twitter.

Isso pode ser feito acessando a página de [desenvolvedores](https://developer.twitter.com) do twitter (logado na sua conta) e clicar em _apply for a development account_

Após sua conta ser aceita (as vezes é rápido, as vezes demora...) você precisa criar um app e guardar as credenciais dele.

- Consumer API keys
- Access token & access token secret

## Vamos a luta!

Agora de posse de tudo que é necessário, mãos a obra!
"""

import tweepy
import numpy as np
from textblob import TextBlob

consumer_key='your_consumer_key'
consumer_secret='consumer_secret'

access_token='access_token'
access_token_secret='access_token_secret'

"""Agora, pra confirmar se deu tudo certo, façamos a autenticação na API do twitter"""

auth = tweepy.OAuthHandler(consumer_key,consumer_secret)
auth.set_access_token(access_token,access_token_secret)

api = tweepy.API(auth)

api

"""Se deu tudo certo, vamos ao que interessa, buscar os dados para trabalhar!!!"""

tweets = api.search('Bolsonaro -filter:retweets')

"""O trecho "-filter:retweets" serve para que os retweets não sejam trazidos para nossa base, evitando que haja repetição de dados

Agora, vamos iterar sobre todos os tweets recuperados, colocando o conteúdo de texto (tweet.text) em um TextBlob
"""

for tweet in tweets:
  print(TextBlob(tweet.text))

"""Um "problema" que temos é que o algoritmo de análise de sentimentos do TextBlob foi treinado em inglês, portanto usaremos um recurso que faz a tradução para inglês dos tweets que tiverem em outros idiomas. 

Primeiro criaremos uma função que detecta se o tweet está em inglês
"""

def is_english(text):
  if text.detect_language() == "en":
    return True
  return False

"""Dentro do laço for vamos verificar se o texto está em inglês, se não estiver faremos a tradução deste. Em seguida, faremos a análise de sentimentos"""

for tweet in tweets:
  text = TextBlob(tweet.text)
  
  if not is_english(text):
    text = TextBlob(str(text.translate(to='en')))
  
  print('Tweet: ' + tweet.text)
  print('Polarity: ' + str(text.sentiment.polarity) + " \ " + str(text.sentiment.subjectivity))
  print('.....................')